### PR TITLE
Enable module level hiera file

### PR DESCRIPTION
**Pull request by traylenator**

### CODE REVIEW

**Comment by traylenator** [comment]
This seems to easy. Surely missing somehing..

**Comment by bastelfreak** [comment]
Data in modules is nice if there is a lot of logic in a params.pp file. This can be abstracted into hiera and somtimes it becomes more readable. This module only has some default vaules in the init.pp. Do we get any value from migrating to data in modules?

**Comment by traylenator** [comment]
Hi,
The very next patch was to manage the different defaults between debian and redhat I think 
e.g https://github.com/voxpupuli/puppet-nscd/pull/30

**Comment by traylenator** [comment]
And https://github.com/voxpupuli/puppet-nscd/issues/40 aslo.

**Pull request closed without merging**
