### PR TITLE
On Ubuntu - nscd runs as root by default. fails to start as nscd user.

### PR DESCRIPTION
**Pull request by KlavsKlavsen**
Alternatively one could change how Ubuntu does things, and create nscd user to run it as.. (and what else might possibly need changing for it to run as nscd user).. but that would be go to against Ubuntu defaults.

### CODE REVIEW

**Comment by traylenator** [comment]
Leave it running as root on ubuntu if that is what it expects.

**Comment by KlavsKlavsen** [comment]
And that is what the PR does. it works great here :)

**Comment by traylenator** [comment]
I think the way to do this os to have a parameter nscd::user defaulting to 'nscd' on centos and 'undef'  elsewhere.

How about we add some module level hiera data to support multiple operating systems and this will be a lot cleaner. No doubt other differences will crop up.

**Comment by KlavsKlavsen** [comment]
if you want to for hiera version 5.. that puts a requirement on it being new puppet versions.. (can't remember exactly how new.. but Puppet 5 probably - or atleast latest puppet 4.x

**Pull request closed without merging**
