### PR TITLE
Prepare 2.0.0 release

### PR DESCRIPTION
**Pull request by traylenator**

### CODE REVIEW

**Comment by traylenator** [comment]
So I did a detailed commit message here in a PR 
https://github.com/voxpupuli/puppet-nscd/pull/11
but alas none of it makes it to the changelog.

**Comment by alexjfisher** [comment]
@traylenator I've just updated the #11 PR title.  If you regenerate the changelog, hopefully it'll be good enough.  (Feel free to reword if you think I've missed anything).

**Comment by alexjfisher** [comment]
Do you think the README should also mention something about the migration to voxpupuli and the change of namespace?

**Comment by traylenator** [comment]
CHANGELOG updated and obsoletion comment added to README

**Comment by alexjfisher** [comment]
I just ran them manually, and all the tests do work on puppet 5.
@traylenator Do you think it's worth changing `"version_requirement": ">= 4.6.1 < 5.0.0"` to `"version_requirement": ">= 4.6.1 < 6.0.0"` in [metadata.json](https://github.com/voxpupuli/puppet-nscd/pull/20/files#diff-490694a9db8f7a371538da1abe484314R21)?

@bastelfreak Is there a plan for adding puppet 5 to the travis test matrix?

**Comment by traylenator** [comment]
We added puppet 5 to [our](https://gitlab.cern.ch/ai/it-puppet-modulesync-configs/blob/master/moduleroot/.gitlab-ci.yml#L63) matrix and has so far we have seen nothing interesting.

**Comment by bastelfreak** [comment]
@traylenator can you rebase? I just noticed that we never released this module, we should finally do it.

**Comment by traylenator** [comment]
This was released in the end so think this is now dead.

**Pull request closed without merging**
