### PR TITLE
change module dependency syntax

### LINKED ISSUE #72: Dependency is incorrectly listed
In the `metadata.json` you see:
```
  "dependencies": [
    {
      "name": "puppetlabs-stdlib",
      "version_requirement": ">= 4.13.1 < 9.0.0"
    }
  ],
```

The name of the module is incorrect. It should be "puppetlabs/stdlib" with a slash.

### PR DESCRIPTION
**Pull request by SimonHoenscheid**
I checked a few vox modules and these seem to use the / notation, so here is a PR to make this uniform

Fixes #72

### CODE REVIEW

**Comment by silug** [comment]
If anything, wouldn't we be better off using author-module?  I was under the impression that author/module was the older way to do it.

**Comment by kenyon** [comment]
Either one works, but the docs say to use the dash format:

https://www.puppet.com/docs/puppet/8/modules_publishing.html#modules_publishing-publishing-name-module

>  Tip: Although the Forge expects to receive modules named username-module, its web interface presents them as username/module. Always use the username-module style in your metadata files and when issuing commands.

**Comment by kenyon** [comment]
And then in their own examples they use slashes 🤷 https://www.puppet.com/docs/puppet/8/modules_metadata

**Comment by bastelfreak** [comment]
Vox Pupuli usually uses `/`:

```
$ grep 'puppetlabs-stdlib' puppet-*/metadata.json | wc -l
29
bastelfreak@bastelfreak-nb ~/code/modulesync_config/modules/voxpupuli $ grep 'puppetlabs/stdlib' puppet-*/metadata.json | wc -l
125
bastelfreak@bastelfreak-nb ~/code/modulesync_config/modules/voxpupuli $
```

**Pull request merged**
